apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: queue

  ports:
    - name: http
      port: 8161
      nodePort: 30070

    - name: endpoint
      port: 61616

  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: webapp

spec:
  # Defines which pods are going to be represented by this Service. For example
  # Select pod where app = webapp
  selector:
    app: webapp

  ports:
    - name: http
      port: 80
      nodePort: 30080
  type: NodePort



---
apiVersion: v1
kind: Service
metadata:
  # The name gets addeded to Kubernetes dns, so this must be accurate
  name: fleetman-position-tracker

spec:
  # Defines which pods are going to be represented by this Service. For example
  # Select pod where app = webapp
  selector:
    app: position-tracker

  ports:
    - name: http
      port: 8080
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  # The name gets addeded to Kubernetes dns, so this must be accurate
  name: api-gateway

spec:
  # Defines which pods are going to be represented by this Service. For example
  # Select pod where app = webapp
  selector:
    app: api-gateway

  ports:
    - name: http
      port: 8080
  type: ClusterIP


